#!/usr/bin/python

# This tool is written as a part of the course TDDD17 
# at the Linkoping University, Sweden (2015).
# Support: josgu898@student.liu.se

# test to use GIT---Rahul

#!/usr/bin/bash

# THis is SOOOO not done yet!

# Find PL nodes that listen on TCP port 22 and create a nice list

# sudo nmap -iL targets/nodes_clean.txt  -PN -p ssh  > ../ssh_scan.txt
# cat ssh_scan.txt  | grep -B 4 'open' | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep '^Nmap' | awk '{print $5}' | sort > ssh_nodes.txt

# sudo nmap -iL targets/nodes_clean.txt  -PN -p ssh  > ../ssh_scan.txt | grep -B 4 'open' | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep '^Nmap' | awk '{print $5}' | sort 

